const SOURCES={loto6:{base:'https://www.mizuhobank.co.jp/takarakuji/apl/txt/loto6/',pick:6,bonus:1,max:43},loto7:{base:'https://www.mizuhobank.co.jp/takarakuji/apl/txt/loto7/',pick:7,bonus:2,max:37}};
function decode(buf){const u=new Uint8Array(buf);for(const enc of ['shift_jis','utf-8']){try{const s=new TextDecoder(enc).decode(u);if(/CSV|ロト|本数字|ボーナス|抽せん/.test(s))return s}catch{}}return new TextDecoder().decode(u)}
function dateOf(s){const m=String(s).match(/(20\d{2})\D+(\d{1,2})\D+(\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:''}
function numbers(s,max){return (String(s).match(/\d{1,2}/g)||[]).map(Number).filter(n=>n>=1&&n<=max)}
function valid(d,c){return d&&d.no>0&&d.date&&d.nums.length===c.pick&&new Set(d.nums).size===c.pick&&d.bonus.length===c.bonus&&new Set(d.bonus).size===c.bonus&&!d.bonus.some(n=>d.nums.includes(n))}
function parse(text,file,c){const lines=String(text).replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);const all=lines.join('\n');let no=Number((all.match(/第\s*(\d+)\s*回/)||[])[1]||0);if(!no){const m=file.match(/(\d{4})\.csv$/i);if(m)no=Number(m[1])}const date=dateOf(all);let main=[],bonus=[];for(let i=0;i<lines.length;i++){if(/本数字/.test(lines[i]))main=numbers(lines[i]+' '+(lines[i+1]||''),c.max).slice(-c.pick);if(/ボーナス/.test(lines[i]))bonus=numbers(lines[i]+' '+(lines[i+1]||''),c.max).slice(-c.bonus)}if(main.length!==c.pick||bonus.length!==c.bonus){const rows=lines.map(x=>x.split(/[\t,]/).map(y=>y.replace(/^"|"$/g,'').trim()));for(const row of rows){const vals=row.map(Number).filter(Number.isFinite);if(vals.length>=c.pick+c.bonus+1){const offset=vals[0]>100?1:0;const cand=vals.slice(offset,offset+c.pick);const b=vals.slice(offset+c.pick,offset+c.pick+c.bonus);if(cand.every(n=>n>=1&&n<=c.max)&&b.every(n=>n>=1&&n<=c.max)){main=cand;bonus=b;break}}}}
const d={no,date,nums:[...main].sort((a,b)=>a-b),bonus:[...bonus].sort((a,b)=>a-b)};if(!valid(d,c))throw new Error(`CSV解析失敗 ${file}: no=${no} date=${date} main=${main} bonus=${bonus}`);return d}
async function get(url){const r=await fetch(url,{cache:'no-store',headers:{'user-agent':'Mozilla/5.0','accept':'text/plain,text/csv,*/*'}});if(!r.ok)throw new Error(`${url} HTTP ${r.status}`);return r}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store, max-age=0');res.setHeader('Access-Control-Allow-Origin','*');const game=String(req.query?.game||'loto6');const c=SOURCES[game];if(!c)return res.status(400).json({ok:false,error:'未対応ゲーム'});const diagnostics=[];try{const nr=await get(c.base+'name.txt?ts='+Date.now());const nameText=decode(await nr.arrayBuffer());const files=[...new Set((nameText.match(/[A-Za-z]\d{6,10}\.csv/gi)||[]))];files.sort((a,b)=>Number((b.match(/(\d{4})\.csv$/i)||[])[1]||0)-Number((a.match(/(\d{4})\.csv$/i)||[])[1]||0));if(!files.length)throw new Error('name.txtからCSV名を検出できません');for(const file of files.slice(0,12)){for(const candidate of [file,file.toUpperCase(),file.toLowerCase()]){try{const cr=await get(c.base+candidate+'?ts='+Date.now());const draw=parse(decode(await cr.arrayBuffer()),candidate,c);return res.status(200).json({ok:true,game,draw:{...draw,verified:true,source:'みずほ銀行公式CSV'},filename:candidate,checkedAt:new Date().toISOString(),diagnostics})}catch(e){diagnostics.push(String(e.message||e))}}}throw new Error('候補CSVを取得・解析できません')}catch(e){return res.status(502).json({ok:false,game,error:String(e.message||e),checkedAt:new Date().toISOString(),diagnostics:diagnostics.slice(-20)})}}
