const GAME={loto6:{paypay:"https://www.paypay-bank.co.jp/lottery/loto/loto6recent.html",max:43,pick:6,bonus:1,mizuho:"https://www.mizuhobank.co.jp/takarakuji/apl/txt/loto6/"},loto7:{paypay:"https://www.paypay-bank.co.jp/lottery/loto/loto7recent.html",max:37,pick:7,bonus:2,mizuho:"https://www.mizuhobank.co.jp/takarakuji/apl/txt/loto7/"}};
const headers={"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile Safari/604.1","Accept":"text/html,text/plain,text/csv,*/*","Accept-Language":"ja-JP,ja;q=0.9"};
async function get(url){const r=await fetch(url,{headers,redirect:"follow",cache:"no-store"});if(!r.ok)throw new Error(`${new URL(url).hostname} HTTP ${r.status}`);return r}
function strip(s){return s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ")}
function normDate(s){const m=s.match(/(20\d{2})[年\/\-.](\d{1,2})[月\/\-.](\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`:""}
function validate(d,c){return d&&d.no>0&&d.nums.length===c.pick&&new Set(d.nums).size===c.pick&&d.bonus.length===c.bonus&&new Set(d.bonus).size===c.bonus&&![...d.bonus].some(x=>d.nums.includes(x))&&[...d.nums,...d.bonus].every(x=>x>=1&&x<=c.max)}
function parsePayPay(html,c){const ifr=[...html.matchAll(/<iframe[^>]+src=["']([^"']+)/gi)].map(m=>new URL(m[1],c.paypay).href);const txt=strip(html);const matches=[...txt.matchAll(/第\s*(\d+)\s*回/g)];for(let z=matches.length-1;z>=0;z--){const m=matches[z],no=+m[1],chunk=txt.slice(m.index,m.index+900);const date=normDate(chunk);let main=(chunk.match(/本数字\s*([0-9\s・,，-]{10,80})/)||[])[1]||"";let bon=(chunk.match(/ボーナス(?:数字)?\s*([0-9\s・,，-]{2,40})/)||[])[1]||"";let nums=(main.match(/\d{1,2}/g)||[]).map(Number).slice(0,c.pick);let bonus=(bon.match(/\d{1,2}/g)||[]).map(Number).slice(0,c.bonus);const d={no,date,nums:nums.sort((a,b)=>a-b),bonus:bonus.sort((a,b)=>a-b)};if(validate(d,c))return d}return{iframes:ifr}}
async function paypay(c){let html=await (await get(c.paypay)).text(),p=parsePayPay(html,c);if(p.no)return p;for(const u of p.iframes||[]){const h=await (await get(u)).text(),d=parsePayPay(h,c);if(d.no)return d}throw new Error("PayPay銀行ページを解析できません")}
function decode(buf){for(const e of ["shift_jis","utf-8"]){try{const t=new TextDecoder(e).decode(buf);if(/ロト|本数字|ボーナス/.test(t))return t}catch{}}return new TextDecoder().decode(buf)}
function parseMizuho(text,file,c){const no=+((text.match(/第\s*(\d+)\s*回/)||[])[1]||(file.match(/(\d{4})\.CSV/i)||[])[1]||0),date=normDate(text);const lines=text.replace(/\r/g,"").split("\n");let nums=[],bonus=[];for(let i=0;i<lines.length;i++){if(/本数字/.test(lines[i]))nums=(lines.slice(i,i+3).join(" ").match(/\d{1,2}/g)||[]).map(Number).filter(n=>n<=c.max).slice(-c.pick);if(/ボーナス/.test(lines[i]))bonus=(lines.slice(i,i+2).join(" ").match(/\d{1,2}/g)||[]).map(Number).filter(n=>n<=c.max).slice(-c.bonus)}const d={no,date,nums:nums.sort((a,b)=>a-b),bonus:bonus.sort((a,b)=>a-b)};if(!validate(d,c))throw new Error("みずほCSV解析失敗");return d}
async function mizuho(c){const nr=await get(c.mizuho+"name.txt"),nt=decode(await nr.arrayBuffer()),files=[...new Set(nt.match(/[A-Z]\d+\.CSV/gi)||[])].sort((a,b)=>+((b.match(/(\d{4})/)||[])[1]||0)-+((a.match(/(\d{4})/)||[])[1]||0));for(const f of files.slice(0,5)){try{const r=await get(c.mizuho+f);return parseMizuho(decode(await r.arrayBuffer()),f,c)}catch{}}throw new Error("みずほ銀行公式CSV取得失敗")}
module.exports=async(req,res)=>{res.setHeader("Cache-Control","no-store,max-age=0");const game=String(req.query.game||"loto6"),c=GAME[game];if(!c)return res.status(400).json({ok:false,error:"未対応ゲーム"});const errors=[];for(const [source,fn] of [["PayPay銀行 過去10回当せん情報",paypay],["みずほ銀行 公式CSV",mizuho]]){try{const d=await fn(c);return res.status(200).json({ok:true,game,draw:{...d,verified:true,source},source,checkedAt:new Date().toISOString()})}catch(e){errors.push(`${source}: ${e.message}`)}}return res.status(502).json({ok:false,game,error:errors.join(" / "),checkedAt:new Date().toISOString()})};